### PR TITLE
Fixes #62: Error getting sleep data

### LINKED ISSUE #62: Code stopped working, Error 503 for sleep data
I have been using this code for a couple months and it was working perfectly the last time I checked it at the end of January 2021. Now when I run it I get an error trying to call sleep_get 

This is the line that causes the error: 
`sleep = api.sleep_get(startdate=arrow.get('2021-01-20T21:23:58.970460+05:00'), enddate=arrow.utcnow(), data_fields=list(GetSleepField))
`
However using the line to use sleep_get_summary is working perfectly, with the same inputs (startdate and enddate).

Now when I try to get the sleep data, I get the following error:

> InvalidParamsException                    Traceback (most recent call last)
> <ipython-input-67-ec2e993653ad> in <module>
> ----> 1 sleep = api.sleep_get(data_fields = [f for f in GetSleepField], startdate=arrow.get('2021-01-20T21:23:58.970460+07:00'), enddate=arrow.utcnow())
> 
> c:\users\rachel\appdata\local\programs\python\python38\lib\site-packages\withings_api\__init__.py in sleep_get(self, data_fields, startdate, enddate)
>     178         update_params(params, "action", "get")
>     179 
> --> 180         return SleepGetResponse(**self.request(path=self.PATH_V2_SLEEP, params=params))
>     181 
>     182     def sleep_get_summary(
> 
> c:\users\rachel\appdata\local\programs\python\python38\lib\site-packages\withings_api\__init__.py in request(self, path, params, method)
>      76     ) -> Dict[str, Any]:
>      77         """Request a specific service."""
> ---> 78         return response_body_or_raise(
>      79             self._request(method=method, path=path, params=params)
>      80         )
> 
> c:\users\rachel\appdata\local\programs\python\python38\lib\site-packages\withings_api\common.py in response_body_or_raise(data)
>     823         raise AuthFailedException(status=status)
>     824     if status in STATUS_INVALID_PARAMS:
> --> 825         raise InvalidParamsException(status=status)
>     826     if status in STATUS_UNAUTHORIZED:
>     827         raise UnauthorizedException(status=status)
> 
> InvalidParamsException: Error code 503
> 

Thanks!

### PR DESCRIPTION
**Pull request by ronaldheft**
I tracked down the issue reported in #62 (also affecting https://github.com/home-assistant/core/issues/47329).

The root of the issue is the `arrow` dependency does not support python 3.9. I bumped the dependency and all appears to be working now.

### CODE REVIEW

**Comment by ronaldheft** [comment]
Apologies that this PR is failing the linting checks. Trying to run the script locally, but I'm on Mac OS X Big Sur, and it appears `typed-ast` does not have a compiled version for it.

```
ERROR: typed_ast-1.4.1-cp39-cp39-macosx_10_15_x86_64.whl is not a supported wheel on this platform.
```

I unfortunately do not have another machine at the moment to run the linting script.

**Comment by ronaldheft** [comment]
Got the setup script running in a VSCode python docker container, and I saw tests were failing with my change, which pointed me in a different direction. It appears the issue is with the dependency `arrow`. The version used does not support python 3.9. I'm updating the dependency, rebasing this PR, and will push shortly.

**Comment by ronaldheft** [comment]
Okay, all fixed up with passing tests. Ready to merge when approved.

**Comment by GGI1982** [comment]
Please @vangorra accept PR so we can fix our problem

**Comment by GGI1982** [comment]
> Okay, all fixed up with passing tests. Ready to merge when approved.

Thank you for your precious help

**Pull request merged**
