### PR TITLE
Use OAuth2Session hooks to process reply

### PR DESCRIPTION
**Pull request by nbogojevic**
Hi @vangorra , the changes in oauth2 endpoint on Withings side are much bigger and incompatible out of the box with `OAuth2Session` and `oauthlib`. 

There is a need to add `access_token_response` and `refresh_token_response` hooks to modify response content and make it understandable by `oauthlib`.

For reference, the same logic is applied for [other oauth2 services (fitbit, linked-in or mailchimp)](https://github.com/search?q=register_compliance_hook&type=Code)

### CODE REVIEW

**Comment by mkaatman** [comment]
Thanks for working on this Nenad

**Comment by Madj42** [comment]
@vangorra will we be able to get the this and the other changes incorporated soon?

**Comment by Madj42** [comment]
@vangorra I'm not trying to be a pest but it looks like the build issues were potentially solved with this commit.  Any chance you could merge this commit?

**Comment by mkaatman** [comment]
I think the old API is shutdown in 2 days

**Comment by Madj42** [comment]
> @vangorra I'm not trying to be a pest but it looks like the build issues were potentially solved with this commit. Any chance you could merge this commit?

That or I was going to suggest that if you did move on, maybe give one of us the ability to monitor pull requests and merge them.  I know you don't know me but I'd be happy to help with this if it helps you out.

**Comment by craibo** [comment]
Thank you @vangorra and @nbogojevic

**Pull request merged**
